// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wJ60iIe6VVgV1R358UKyqNePA8022Mc',
    appId: '1:28068623394:android:6ee85d7d6d0217606a067b',
    messagingSenderId: '28068623394',
    projectId: 'teatally-d1b86',
    storageBucket: 'teatally-d1b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJuu2KiJ5BoM8XXRnO_lQiY6KNNrWe88',
    appId: '1:28068623394:ios:52eeecd9557b3b0a6a067b',
    messagingSenderId: '28068623394',
    projectId: 'teatally-d1b86',
    storageBucket: 'teatally-d1b86.firebasestorage.app',
    androidClientId: '28068623394-1gid21q03k9f651i37k4cc726uei6sip.apps.googleusercontent.com',
    iosClientId: '28068623394-3aopa4j0598i767uoljqfqjr3bsbalc0.apps.googleusercontent.com',
    iosBundleId: 'com.teatally.pro',
  );

}